#!/usr/bin/env sh
# Arrmada installer — one-shot first-run setup. Idempotent; safe to re-run.
#
#   git clone https://github.com/tristenlammi/Arrmada && cd Arrmada
#   ./install.sh                  # core stack (app + qBittorrent + FlareSolverr)
#   ./install.sh --with-prowlarr  # also start the optional Prowlarr indexer manager
#
# It creates .env (asks for your TMDB key, user/group, and where your media lives),
# puts the database in ./data (inside this app folder), and starts everything.
# Update later with:  ./update.sh
set -eu
cd "$(dirname "$0")"

say() { printf '%s\n' "$*"; }
ask() { # ask "prompt" "default" -> echoes the answer (default if non-interactive/blank)
  _p="$1"; _d="${2:-}"; _a=""
  if [ -t 0 ]; then printf '%s' "$_p" >&2; read -r _a || _a=""; fi
  [ -z "$_a" ] && _a="$_d"
  printf '%s' "$_a"
}

# ── prerequisites ──────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  say "✗ Docker isn't installed (or not on PATH). Install Docker, then re-run ./install.sh" >&2; exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  say "✗ 'docker compose' (v2) isn't available. Update Docker Engine, then re-run." >&2; exit 1
fi

# ── .env (created once, never overwritten) ──────────────────────────────────────
if [ ! -f .env ]; then
  say "First run — let's set up .env."

  PORT=$(awk 'BEGIN { srand(); print int(20000 + rand() * 40000) }')

  KEY="${ARRMADA_TMDB_API_KEY:-}"
  [ -z "$KEY" ] && KEY=$(ask "TMDB API key (free: themoviedb.org — needed for Movies & TV; Enter to skip): " "")

  say ""
  say "Run Arrmada as which user? On Unraid this is usually 99 (nobody) / 100 (users)."
  PUID=$(ask "  PUID [1000]: " "1000")
  PGID=$(ask "  PGID [1000]: " "1000")

  say ""
  say "Where does your media live? Give the folder that CONTAINS your libraries + downloads"
  say "(e.g. /mnt/user/masterdirectory). Leave blank to use Arrmada's own managed storage."
  MEDIA=$(ask "  Media folder [blank = managed]: " "")

  {
    say "# ─── Arrmada configuration ─── edit, then ./update.sh to apply ───"
    say ""
    say "# Movie/TV metadata (required for Movies & TV). Free: https://www.themoviedb.org/settings/api"
    say "ARRMADA_TMDB_API_KEY=$KEY"
    say "ARRMADA_OMDB_API_KEY="
    say ""
    say "ARRMADA_PORT=7878"
    say "ARRMADA_QBIT_PORT=$PORT"
    say "ARRMADA_AUTH_ENABLED=false"
    say ""
    say "# Run as this user/group (Unraid: 99 / 100)."
    say "ARRMADA_PUID=$PUID"
    say "ARRMADA_PGID=$PGID"
    say ""
    say "# Database + config live here, inside this app folder (appdata)."
    say "ARRMADA_DATA_HOST=./data"
    if [ -n "$MEDIA" ]; then
      say ""
      say "# Your media folder is mounted at /storage inside the app. Point each library at"
      say "# its subfolder (adjust to your actual folder names, or set them in the app later)."
      say "ARRMADA_STORAGE_HOST=$MEDIA"
      say "ARRMADA_MOVIES_DIR=/storage/media/movies"
      say "ARRMADA_TV_DIR=/storage/media/tvshows"
      say "ARRMADA_EBOOKS_DIR=/storage/media/ebooks"
      say "ARRMADA_AUDIOBOOKS_DIR=/storage/media/audiobooks"
      say "ARRMADA_DOWNLOADS_DIR=/storage/torrents"
    fi
  } > .env

  # Generate the /storage mount when a real media folder was given.
  if [ -n "$MEDIA" ] && [ ! -f docker-compose.override.yml ]; then
    cat > docker-compose.override.yml <<EOF
# Auto-generated by install.sh — mounts your media folder at /storage in both containers.
services:
  arrmada-app:
    volumes:
      - $MEDIA:/storage
  arrmada-qbittorrent:
    volumes:
      - $MEDIA:/storage
EOF
    say "✓ Wrote docker-compose.override.yml (your media → /storage)"
  fi

  mkdir -p ./data
  say "✓ Wrote .env  (BitTorrent port: $PORT, user: $PUID:$PGID)"
  [ -z "$KEY" ] && say "  ! No TMDB key — add ARRMADA_TMDB_API_KEY to .env for Movies/TV, then ./update.sh"
else
  say ".env already exists — keeping your settings."
fi

# ── build + start ──────────────────────────────────────────────────────────────
PROFILES=""
[ "${1:-}" = "--with-prowlarr" ] && PROFILES="--profile prowlarr"

say "Building and starting Arrmada… (the first build compiles everything — a few minutes)"
# shellcheck disable=SC2086
docker compose $PROFILES up -d --build

WEBPORT=$(grep -E '^ARRMADA_PORT=' .env | cut -d= -f2)
say ""
say "✓ Arrmada is up.  Open http://localhost:${WEBPORT:-7878}"
say "  Update anytime with:  ./update.sh"
