package subtitles

import (
	"context"
	"errors"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/tristenlammi/arrmada/internal/settings"
	"github.com/tristenlammi/arrmada/internal/store"
)

const fakeSRT = "1\n00:00:01,000 --> 00:00:02,000\nHello.\n"

// fakeProvider stands in for OpenSubtitles: per-language results or errors, and a count
// of the searches it was asked for.
type fakeProvider struct {
	mu          sync.Mutex
	canDownload bool
	paused      bool
	results     map[string][]SubtitleResult
	searchErr   map[string]error
	downloadErr error
	searches    int
	searched    []string
}

func (p *fakeProvider) Available() bool   { return true }
func (p *fakeProvider) CanDownload() bool { return p.canDownload }
func (p *fakeProvider) Paused() bool      { return p.paused }
func (p *fakeProvider) Search(_ context.Context, r SearchRequest) ([]SubtitleResult, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.searches++
	p.searched = append(p.searched, r.Language)
	if err := p.searchErr[r.Language]; err != nil {
		return nil, err
	}
	return p.results[r.Language], nil
}
func (p *fakeProvider) Download(context.Context, string) ([]byte, error) {
	if p.downloadErr != nil {
		return nil, p.downloadErr
	}
	return []byte(fakeSRT), nil
}

// fakeAI writes a sidecar instead of running whisper, and records what it was asked for.
type fakeAI struct {
	avail, transcribe, translate bool
	fail                         error
	calls                        []string // "<lang>/<transcribe|translate>"
}

func (a *fakeAI) available() bool { return a.avail }
func (a *fakeAI) canRun(translate bool) bool {
	if translate {
		return a.translate
	}
	return a.transcribe
}
func (a *fakeAI) generate(_ context.Context, _, _, srt, lang string, translate bool, _ int, _ func(int)) error {
	a.calls = append(a.calls, lang+"/"+ifElse(translate, "translate", "transcribe"))
	if a.fail != nil {
		return a.fail
	}
	return os.WriteFile(srt, []byte(fakeSRT), 0o644)
}
func (a *fakeAI) Backend() string { return "cpu" }
func (a *fakeAI) Device() string  { return "" }

// ladderFixture builds a Service whose seams point at a synthetic video in a temp dir:
// nothing is probed, extracted or transcribed for real.
func ladderFixture(t *testing.T, langs string, mi *mediaInfo, prov Provider, ai aiRunner) (*Service, string) {
	t.Helper()
	st, err := store.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = st.Close() })
	set := settings.NewService(st.DB())
	if err := set.Set(context.Background(), keyLanguages, langs); err != nil {
		t.Fatal(err)
	}
	video := filepath.Join(t.TempDir(), "Movie (2020).mkv")
	if err := os.WriteFile(video, []byte("not really a video"), 0o644); err != nil {
		t.Fatal(err)
	}
	s := &Service{
		settings: set,
		provider: prov,
		log:      slog.New(slog.NewTextHandler(io.Discard, nil)),
		wake:     make(chan struct{}, 1),
		ai:       ai,
	}
	s.resolve = func(context.Context, *Job) (fileRef, bool) {
		return fileRef{Path: video, Title: "Movie", Year: 2020, MediaKey: "m:1"}, true
	}
	s.probe = func(context.Context, string) (*mediaInfo, error) { return mi, nil }
	s.extract = func(context.Context, string, []extractPick) error {
		t.Error("extract ran with no embedded text track")
		return nil
	}
	return s, video
}

// runJob queues and processes one movie job synchronously.
func runJob(s *Service) *Job {
	job := s.enqueue(&Job{Kind: "movie", MovieID: 1, Title: "Movie", Priority: PrioManual})
	s.pop()
	s.process(context.Background(), job)
	return job
}

func englishAudio() *mediaInfo {
	return &mediaInfo{AudioLangs: []string{"eng"}, Audio: []AudioTrack{{Index: 0, Lang: "eng"}}}
}

func assertSidecar(t *testing.T, video, lang string) {
	t.Helper()
	fi, err := os.Stat(sidecarPath(video, lang))
	if err != nil || fi.Size() == 0 {
		t.Errorf("no %s sidecar written (err=%v)", lang, err)
	}
}

// With OpenSubtitles configured, a language it has no match for is generated by the AI in
// the same job, and the note says both things happened.
func TestProcessFallsThroughToAIOnNoMatch(t *testing.T) {
	prov := &fakeProvider{canDownload: true}
	ai := &fakeAI{avail: true, transcribe: true, translate: true}
	s, video := ladderFixture(t, "en", englishAudio(), prov, ai)
	job := runJob(s)
	assertSidecar(t, video, "en")
	if job.State != StateDone {
		t.Errorf("state = %q, want done", job.State)
	}
	if !strings.Contains(job.Note, "no OpenSubtitles match") || !strings.Contains(job.Note, "AI-generated") {
		t.Errorf("note = %q, want it to name both rungs", job.Note)
	}
	if prov.searches != 1 || len(ai.calls) != 1 || ai.calls[0] != "en/transcribe" {
		t.Errorf("searches=%d ai=%v, want one search then one transcription", prov.searches, ai.calls)
	}
}

// While the download quota is paused, the job makes no search request at all and goes
// straight to AI.
func TestProcessQuotaPausedSkipsSearch(t *testing.T) {
	prov := &fakeProvider{canDownload: true, paused: true}
	ai := &fakeAI{avail: true, transcribe: true}
	s, video := ladderFixture(t, "en", englishAudio(), prov, ai)
	job := runJob(s)
	if prov.searches != 0 {
		t.Errorf("%d searches while the quota is paused, want 0", prov.searches)
	}
	assertSidecar(t, video, "en")
	if job.State != StateDone || job.Note != "en: quota spent → AI-generated" {
		t.Errorf("state=%q note=%q", job.State, job.Note)
	}
}

// A quota that runs out part-way through stops further searches, but every language left
// still reaches the AI rung.
func TestProcessQuotaHitMidJobLeavesRestForAI(t *testing.T) {
	prov := &fakeProvider{canDownload: true, downloadErr: ErrQuotaExhausted,
		results: map[string][]SubtitleResult{"en": {{FileID: "1"}}, "es": {{FileID: "2"}}}}
	ai := &fakeAI{avail: true, transcribe: true}
	mi := &mediaInfo{AudioLangs: []string{"eng", "spa"}, Audio: []AudioTrack{{Index: 0, Lang: "eng"}, {Index: 1, Lang: "spa"}}}
	s, video := ladderFixture(t, "en,es", mi, prov, ai)
	job := runJob(s)
	if prov.searches != 1 {
		t.Errorf("searches = %d, want 1 (stop asking once the quota is spent)", prov.searches)
	}
	assertSidecar(t, video, "en")
	assertSidecar(t, video, "es")
	if job.Note != "en: quota spent → AI-generated · es: quota spent → AI-generated" {
		t.Errorf("note = %q", job.Note)
	}
}

// An HTTP error from the provider for one language doesn't stop AI making it.
func TestProcessProviderErrorFallsThrough(t *testing.T) {
	prov := &fakeProvider{canDownload: true, searchErr: map[string]error{"en": errors.New("opensubtitles search: HTTP 500")}}
	ai := &fakeAI{avail: true, transcribe: true}
	s, video := ladderFixture(t, "en", englishAudio(), prov, ai)
	job := runJob(s)
	assertSidecar(t, video, "en")
	if job.State != StateDone || job.Note != "en: OpenSubtitles error → AI-generated" {
		t.Errorf("state=%q note=%q", job.State, job.Note)
	}
}

// An embedded text track that extracts to 0 bytes falls through to download, then AI —
// and the empty file doesn't linger as a fake "present" sidecar.
func TestProcessEmptyExtractFallsThrough(t *testing.T) {
	prov := &fakeProvider{canDownload: true}
	ai := &fakeAI{avail: true, transcribe: true}
	mi := englishAudio()
	mi.Subs = []SubTrack{{Index: 0, Codec: "subrip", Lang: "eng", Text: true}}
	s, video := ladderFixture(t, "en", mi, prov, ai)
	var picked []extractPick
	s.extract = func(_ context.Context, _ string, picks []extractPick) error {
		picked = picks
		for _, p := range picks {
			if err := os.WriteFile(p.Path, nil, 0o644); err != nil {
				return err
			}
		}
		return nil
	}
	job := runJob(s)
	if len(picked) != 1 || picked[0].Index != 0 {
		t.Fatalf("extract picks = %+v, want stream 0", picked)
	}
	assertSidecar(t, video, "en")
	want := "en: embedded track was empty → no OpenSubtitles match → AI-generated"
	if job.State != StateDone || job.Note != want {
		t.Errorf("state=%q note=%q, want %q", job.State, job.Note, want)
	}
}

// A good extraction ends the ladder for that language: no search, no AI.
func TestProcessExtractStopsTheLadder(t *testing.T) {
	prov := &fakeProvider{canDownload: true}
	ai := &fakeAI{avail: true, transcribe: true}
	mi := englishAudio()
	mi.Subs = []SubTrack{{Index: 2, Codec: "subrip", Lang: "eng", Text: true}}
	s, video := ladderFixture(t, "en", mi, prov, ai)
	s.extract = func(_ context.Context, _ string, picks []extractPick) error {
		for _, p := range picks {
			if err := os.WriteFile(p.Path, []byte(fakeSRT), 0o644); err != nil {
				return err
			}
		}
		return nil
	}
	job := runJob(s)
	assertSidecar(t, video, "en")
	if prov.searches != 0 || len(ai.calls) != 0 || job.Note != "en: extracted" {
		t.Errorf("searches=%d ai=%v note=%q", prov.searches, ai.calls, job.Note)
	}
}

// With no whisper model installed, the note says the AI rung couldn't act and why — never
// "nothing produced".
func TestProcessAIUnavailableNote(t *testing.T) {
	s, _ := ladderFixture(t, "en", englishAudio(), nil, &fakeAI{})
	job := runJob(s)
	if job.State != StateSkipped {
		t.Errorf("state = %q, want skipped", job.State)
	}
	if job.Note != "en: no whisper model installed" {
		t.Errorf("note = %q", job.Note)
	}
	if strings.Contains(job.Note, "nothing produced") {
		t.Error("note still says nothing produced")
	}
}

// Translating foreign audio into English needs large-v3; translating into anything else
// can't be done at all. Both say so.
func TestProcessTranslateNeedsLargeV3(t *testing.T) {
	ai := &fakeAI{avail: true, transcribe: true, translate: false}
	mi := &mediaInfo{AudioLangs: []string{"fre"}, Audio: []AudioTrack{{Index: 0, Lang: "fre"}}}
	s, _ := ladderFixture(t, "en,es", mi, nil, ai)
	job := runJob(s)
	want := "en: needs large-v3 to translate · es: whisper can't translate into es"
	if job.State != StateSkipped || job.Note != want {
		t.Errorf("state=%q note=%q, want %q", job.State, job.Note, want)
	}
	if len(ai.calls) != 0 {
		t.Errorf("generate ran %v without a usable model", ai.calls)
	}
}

// A failed AI run is named with the reason, and doesn't stop the next language.
func TestProcessAIFailureIsNamed(t *testing.T) {
	ai := &fakeAI{avail: true, transcribe: true, fail: errors.New("whisper: exit status 1: out of memory")}
	s, _ := ladderFixture(t, "en", englishAudio(), nil, ai)
	job := runJob(s)
	if job.State != StateSkipped || !strings.HasPrefix(job.Note, "en: AI failed: ") || !strings.Contains(job.Note, "out of memory") {
		t.Errorf("state=%q note=%q", job.State, job.Note)
	}
}

// A stopped job doesn't fall through to the next rung or record failures.
func TestProcessStoppedDoesNotFallThrough(t *testing.T) {
	prov := &fakeProvider{canDownload: true}
	ai := &fakeAI{avail: true, transcribe: true}
	s, _ := ladderFixture(t, "en", englishAudio(), prov, ai)
	job := s.enqueue(&Job{Kind: "movie", MovieID: 1, Title: "Movie"})
	s.pop()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	s.process(ctx, job)
	if job.State != StateCancelled || job.Note != "stopped" {
		t.Errorf("state=%q note=%q", job.State, job.Note)
	}
	if prov.searches != 0 || len(ai.calls) != 0 {
		t.Errorf("searches=%d ai=%v after stop", prov.searches, ai.calls)
	}
}

// The Library chip for a missing language shows the AI fallback only when AI could
// actually make that language.
func TestFillCoverageFallback(t *testing.T) {
	prov := &fakeProvider{canDownload: true}
	cases := []struct {
		name  string
		ai    *fakeAI
		audio []string
		lang  string
		want  string
	}{
		{"download then AI", &fakeAI{avail: true, transcribe: true}, []string{"eng"}, "en", "ai"},
		{"no model", &fakeAI{}, []string{"eng"}, "en", ""},
		{"can't translate into es", &fakeAI{avail: true, transcribe: true, translate: true}, []string{"fre"}, "es", ""},
		{"translate needs large-v3", &fakeAI{avail: true, transcribe: true}, []string{"fre"}, "en", ""},
	}
	for _, c := range cases {
		mi := &mediaInfo{AudioLangs: c.audio}
		s, video := ladderFixture(t, c.lang, mi, prov, c.ai)
		fs := FileSubs{Kind: "movie", Path: video}
		s.fillCoverage(context.Background(), &fs, []string{c.lang}, true)
		if len(fs.Languages) != 1 || fs.Languages[0].Source != "download" || fs.Languages[0].Fallback != c.want {
			t.Errorf("%s: languages = %+v, want source download, fallback %q", c.name, fs.Languages, c.want)
		}
	}
}
